---
- hosts: all
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Grafana repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Grafana Agent
      apt:
        name: grafana-agent
        state: present

    - name: create opt directory for prometheus
      file:
        path: /opt/prometheus
        state: directory

    - name: copy node_exporter.crt
      template:
        src: grafana-agent.yaml
        dest: /etc/grafana-agent.yaml

    - name: Enable and start Grafana Agent service
      service:
        name: grafana-agent
        state: started
        enabled: yes

    - name: Restart Grafana Agent service
      service:
        name: grafana-agent
        state: restarted


- hosts: all
  gather_facts: false
  vars:
    node_exporter_version: 1.5.0
  tasks:
    - name: test connection
      ping:

    - name: create group
      group:
        name: prometheus
        state: present

    - name: create user
      user:
        name: prometheus
        group: prometheus
        createhome: no
        system: yes
        state: present

    - name: create opt directory for prometheus
      file:
        path: /opt/prometheus
        state: directory

    - name: create opt directory for prometheus
      file:
        path: /etc/node-exporter
        state: directory

    - name: download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/prometheus

    - name: unarchive node exporter
      unarchive:
        remote_src: yes
        src: /opt/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /opt/prometheus

    - name: copy config promotheus
      template:
        src: config.yml
        dest: /etc/node-exporter

    - name: copy node_exporter.key
      template:
        src: node_exporter.key
        dest: /etc/node-exporter

    - name: copy node_exporter.crt
      template:
        src: node_exporter.crt
        dest: /etc/node-exporter

    - name: create symlink to node exporter
      file:
        path: /usr/bin/node_exporter
        state: link
        src: /opt/prometheus/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter

    - name: install unit file to systemd
      template:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service

    - name: configure systemd to use service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: node_exporter.service
