---
- name: Deploy Grafana Agent and configure Prometheus scraping
  hosts: all
  tasks:
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Grafana repository key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Grafana Agent
      apt:
        name: grafana-agent
        state: present

    - name: create opt directory for prometheus
      file:
        path: /opt/prometheus
        state: directory

    - name: copy node_exporter.crt
      template:
        src: grafana-agent.yaml
        dest: /etc/grafana-agent.yaml

    - name: Enable and start Grafana Agent service
      service:
        name: grafana-agent
        state: started
        enabled: yes

    - name: Restart Grafana Agent service
      service:
        name: grafana-agent
        state: restarted
